:nofooter:
:toc: left

= Resources for J.S. Bach, _Magnificat_ in D, BWV 243

== Recordings

=== For purchase

Karl M&uuml;nchinger, Stuttgart Chamber Orchestra::
    - CD: https://www.amazon.com/Bach-Art-Fugue-Musical-Offering/dp/B000050GK0/ref=sr_1_fkmr1_1[Amazon.com,window=_blank]
    - High-quality (lossless) download: https://www.prestomusic.com/classical/products/9467923--j-s-bach-magnificat-bwv-243-meine-seel-erhebt-den-herren-cantata-bwv-10:[prestomusic,window=_blank]

Recording search caveats::
    - What you want: J.S. Bach, Magnificat in D, BWV 243
    - What you don’t want: J.S. Bach, Magnificat in E-flat 
    - Also what you don’t want: C.P.E. Bach, Magnificat

=== YouTube performances

https://youtu.be/EsUWG2axB3w[Netherlands Bach Society, Jos van Veldhoven (on period instruments),window=_blank]

https://youtu.be/41blIyHQ0hs[Concentus Musicus Wien, Arnold Schoenberg Choir, Nikolaus Harnoncourt (on period instruments),window=_blank]

https://youtu.be/3EPk6zOaLH0[HR-Symphony Orchestra, Choir of Le Concert Astr&eacute;e, Emmanuelle Haim,window=_blank]

https://youtu.be/zK9i1f3l-rU[Le Concert de nations, La Capella Reial de Catalunya, Jordi Savall, window=_blank]

== Readings

=== Web

https://en.wikipedia.org/wiki/Magnificat_(Bach)[Wikipedia,window=_blank]::

Yes, you read that correctly: the Wikipedia article on Bach's Magnificat is very good.

=== Books

Markus Rathey, _Bach's Major Vocal Works: Music, Drama, Liturgy_ (Yale, 2016)::

Written for a general readership, this book contains discussions of all the major vocal works. Rathey provides a movement-by-movement discussion of the _Magnificat_ and therefore makes an excellent companion for the listener. (https://www.amazon.com/Bachs-Major-Vocal-Works-Liturgy/dp/030021720X/ref=sr_1_1[Amazon.com,window=_blank])

Daniel Melamed, _Hearing Bach's Passions_, Updated edition (Oxford, 2016)::

While not addressing the Magnificat, this book contains some helpful information on the performing practices of  Bach's time. (https://www.amazon.com/Hearing-Bachs-Passions-Daniel-Melamed/dp/0190490128/ref=sr_1_2[Amazon.com,window=_blank])

Christoph Wolff, _Johann Sebastian Bach: The Learned Musician_ (Norton, 2001)::

This is the definitive Bach biography. While it does contain some technical discussions of the music, one can easily skip over them without losing a sense of the contours of Bach's life and career. (https://www.amazon.com/Johann-Sebastian-Bach-Learned-Musician/dp/0393322564/ref=tmm_pap_swatch_0[Amazon.com,window=_blank])